name: Security Scanning Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  security_scan:
    name: Run Security Scans
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          pip install --no-cache-dir -r requirements.txt

      # Static Application Security Testing (SAST) with Semgrep
      - name: Run Semgrep SAST Scan
        continue-on-error: true
        uses: returntocorp/semgrep-action@v1
        with:
            config: p/ci
      
      # Dependency Scanning with Trivy
      - name: Run Trivy Dependency Scan
        uses: aquasecurity/trivy-action@master
        with:
          scan-type: 'fs'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      # Docker Image Security Scanning
      - name: Build Docker Image
        run: docker build -t devsecops-pipeline .

      - name: Run Trivy Docker Image Scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: 'devsecops-pipeline'
          format: 'table'
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

          # Dynamic Application Security Testing (DAST) with OWASP ZAP
      - name: Start Flask App in Docker
        run: |
            docker run -d -p 5000:5000 --name devsecops-app devsecops-pipeline
            sleep 5  # Give Flask some time to start

      - name: Run OWASP ZAP Baseline Scan
        uses: zaproxy/action-baseline@v0.9.0
        with:
            target: "http://localhost:5000"
            fail_action: true  # Fail if high-risk vulnerabilities are found
